image: docker:latest
stages:
  - build
  - restart

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

ux-build:
  stage: build
  script:
    - echo "${COSIGN_PRIVATE_KEY}" > cosign.key
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
    - apk add --update cosign
    - chmod 600 cosign.*
    - cosign sign --key cosign.key $CONTAINER_RELEASE_IMAGE -y | echo -n "y"
    # - docker container rm -f chat-admin
    # - docker run -d -p 4002:4002 --name chat-admin --restart unless-stopped $CONTAINER_RELEASE_IMAGE
  only:
    - main
ux-restart-deployment:
  stage: restart
  image: docker:latest
  script:
    - apk add --no-cache curl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - export PATH=$PATH:/usr/local/bin/
    - echo "$PROD_KUBECONFIG" > kubeconfig.yml
    - export KUBECONFIG=$(pwd)/kubeconfig.yml
    - kubectl --token $PROD_SA_TOKEN rollout restart deployment chat-admin-deployment -n addispay
